### ISSUE TITLE
Issue installing with yarn and npm

### ISSUE THREAD

**Issue by ganymedio** [mcxross/zeroauth#1]
Hello, running `yarn add @mcxross/zero` returned

`error An unexpected error occurred: "https://registry.yarnpkg.com/@mcxross%2fzero: Not found".`

And `npm install @mcxross/zero` returned 

`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@mcxross%2fzero - Not found
npm ERR! 404 
npm ERR! 404  '@mcxross/zero@*' is not in this registry.`

(following installation instructions at https://zeroauth.dev/platform/web/quick-start.html#installation).

**Comment by astinz** [comment]
Hey,

Public snapshots are coming within a week from now.

But you can still use the package via a Node.js private proxy registry. You can use **Verdaccio** for this.
Here's how you can do it:
Install Verdaccio:
``` npm
npm install -g verdaccio
```

Run it:
```bash
$ verdaccio
```

Set it as a proxy:
```bash
npm set registry http://localhost:4873
```

Build ZeroAuth:
```bash
gradlew :zero:jsBrowserDevelopmentWebpack
```

Publish it:
```bash
npm publish
```

You can then use the package as explained in the docs [here]( https://zeroauth.dev/platform/web/quick-start.html#installation)

**Comment by ganymedio** [comment]
Ah cool, thanks so much.
