### ISSUE TITLE
Google deprecating Oauth mechanism

### ISSUE THREAD

**Issue by mattjurenka** [mcxross/zeroauth#3]
Based on [this Google blog post](https://developers.googleblog.com/2023/10/enhancing-oauth-app-impersonation-protections.html#disallowed-android) from this past October it appears that Google is disabling the custom URL scheme this SDK relies on to redirect OAuth requests to the app. Not 100% sure but I believe they will still support https deep linking, with the `.well-known/assetlinks.json` validation setup.

Will this SDK still work with the changes? At minimum I believe the documentation should be updated to not direct users to setup a custom URI schema.

**Comment by astinz** [comment]
It's to be noted that they've disabled it "by default", so technically it'll still be available for those who enable it.
How much control the recommendation gives the SDK is still being explored.

The documentation is fine, for now, it'll be updated as changes are rolled out. And. Don't forget the releases are beta as noted all over, you can wait until everything is stable or can also make a PR...
